const STRINGS = {
  en: {
    AND: 'and',
    CHOOSE_THE_PACK: `Choose the pack you'd like and click 'Pay'`,
    EMAIL: 'Email',
    FIRST_NAME: 'First name',
    FOR: 'for',
    GET_STARTED: 'Pay',
    GO_BACK_AND_CHANGE_PACK: 'Go back and change pack',
    I_AGREE_TO_THE: 'I agree to the',
    LAST_NAME: 'Last name',
    PAY: 'Finish',
    PLEASE_SEND_ME_NEWS: 'Please send me news, articles and relevant content about Oliva',
    PRIVACY_POLICY: 'privacy policy',
    SESSIONS: 'sessions',
    TERMS_OF_USE: 'terms of use',
    WE_NEED_YOU_TO_AGREE_WITH_OUR_TERMS: 'We need you to agree with our terms',
    WE_NEED_YOUR_CARD_DETAILS: 'We need your card details',
    WE_NEED_YOUR_EMAIL: 'We need your email',
    WE_NEED_YOUR_FIRST_NAME: 'We need your first name',
    WE_NEED_YOUR_LAST_NAME: 'We need your last name',
    YOUR_EMAIL_DOESNT_LOOK_RIGHT: "Your email doesn't look right",
    WE_NEED_YOUR_MOBILE_NUMBER: 'We need your mobile number',
    THANKS: 'Thanks!',
    YOUR_PAYMENT_WAS_SUCCESSFUL: 'Your payment was successful',
    WE_SENT_A_PAYMENT_RECEIPT_TO: 'We just sent a payment receipt to',
    WE_ADDED: 'We added',
    SESSIONS_TO_YOUR_ACCOUNT: 'sessions to your account',
    NEXT_TIME_YOU_SEE_YOUR_THERAPIST: 'Next time you see your therapist they will schedule your next session as usual'
  },
  es: {
    AND: 'y',
    CHOOSE_THE_PACK: `Elige el pack que deseas y haz clic en 'Pagar'`,
    EMAIL: 'Email',
    FIRST_NAME: 'Nombre',
    FOR: 'para',
    GET_STARTED: 'Pagar',
    GO_BACK_AND_CHANGE_PACK: 'Volver y cambiar pack',
    I_AGREE_TO_THE: 'Estoy de acuerdo con los',
    LAST_NAME: 'Apellido',
    PAY: 'Finalizar',
    NOW_TO_PICK_A_TIME: 'Ahora vamos a reservar una fecha para tu sesión de afinidad, y ya habremos acabado.',
    PLEASE_SEND_ME_NEWS: 'Recibir noticias, articulos y contenido sobre Oliva',
    PRIVACY_POLICY: 'política de privacidad',
    SESSIONS: 'sesiones',
    TERMS_OF_USE: 'términos y condiciones',
    WE_NEED_YOU_TO_AGREE_WITH_OUR_TERMS: 'Necesitamos que aceptes los términos y condiciones',
    WE_NEED_YOUR_CARD_DETAILS: 'Necesitamos los datos de su tarjeta',
    WE_NEED_YOUR_EMAIL: 'Necesitamos tu email',
    WE_NEED_YOUR_FIRST_NAME: 'Necesitamos tu nombre',
    WE_NEED_YOUR_LAST_NAME: 'Necesitamos tu apellido',
    WE_SENT_AN_EMAIL_TO: 'Acabamos de enviarte un email a {{0}} con todos los detalles de tu sesión de afinidad, y un recibo del pago.',
    YOUR_EMAIL_DOESNT_LOOK_RIGHT: 'Tu email no parece correcto',
    THANKS: '¡Gracias!',
    YOUR_PAYMENT_WAS_SUCCESSFUL: 'Tu pago se ha realizado con éxito',
    WE_SENT_A_PAYMENT_RECEIPT_TO: 'Acabamos de enviarte un recibo del pago a',
    WE_ADDED: 'Hemos añadido',
    SESSIONS_TO_YOUR_ACCOUNT: 'sesiones a tu cuenta',
    NEXT_TIME_YOU_SEE_YOUR_THERAPIST: 'En tu próxima visita con tu terapeuta podrás programar tu siguiente sesión sin problemas'
  }
}

export const getStrings = (languageCode) => STRINGS[languageCode || 'en'];
